#!/bin/bash
# Runs bootstrapping playbooks against all hosts.

if [ $# -lt 2 ]; then
  echo
  echo "Updates all hosts in the specified group by re-running bootstrap."
  echo "Usage: ./update DC ANSIBLE_GROUP (Ansible args...)"
  exit -1
fi

DIR=$(git rev-parse --show-toplevel)

source ${DIR}/utils/spinedc
source ${DIR}/env/bin/activate

# Disables host key checking to support headless provisioning.
export ANSIBLE_HOST_KEY_CHECKING=False

# Purges any local EC2 cache to ensure that new nodes are detected.
export PURGE_EC2_CACHE="true"

export ANSIBLE_GROUP="${1}"
export ANSIBLE_USER="ansibler"
export ANSIBLE_SHOULD_SUDO="True"
shift

ansible-playbook --vault-password-file ~/.vault -e @vault/creds.yml -i ./inventory/ec2 bootstrap.yml "${@}"
